#-------------------------------
# General Site Settings

title: Olive Grove Wellness
logo: logo3.png # You can add own logo
description: # Add your awesome description
baseurl: "" # The subpath of your site, e.g. /blog
url: "" # The base hostname & protocol for your site, e.g. http://example.com

# Preloader
preloader: true # To disable preloader change value to false

menu:
  - url: /
    name: Home
  - url: /categories/
    name: Wellness
  - url: /categories/
    name:
    submenu:
      - url: /recipes/
        name: Recipes
      - url: /nutrition/
        name: Nutrition
      - url: /workout/
        name: workout
  - url: /resources/
    name: Resources
  - url: /contact/
    name: Contact
  - url: /about/
    name: About

# *** NOTE ***
# You can add submenus. For example:

#  menu:
#  - url: /
#    name: Home
#  - url: /travel/
#    name: Travel
#     submenu:
#      - url: /peru/
#        name: Peru
# ----------------------------------

layout_home_page: true # Homepage layout ( two layout is available, you can set the another layout by change the value of layout_home_page "true" to "false")

featured-post-slider: true # You can enable or disable the featured-post-slider using true or false values.

#-------------------------------
# Hero Section
hero:
  hero-subtitle: I'm a registered dietitian and pilates instructure.
  hero-banner: banner-img.png # Add your banner image '/assets/images/'

#-------------------------------
# Author Settings
author:
  name: Hillary Garcia RD

#-------------------------------
# Contact Info
contact:
  email: example@ymail.com
  phone: +90 000 333 22
  address:
    city: Gainesville
    street: Florida

# Contact Form
contact-form: example@ymail.com

# Social links
social:
- {icon: "ti-facebook", link: "#"}
- {icon: "ti-twitter-alt", link: "#"}
- {icon: "ti-linkedin", link: "#"}
- {icon: "ti-github", link: "#"}

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Instagram Feed
instafeed: true # To enable the instafeed, use the value true. To turn off use the value false.
userID: 4044026246
accessToken: 4044026246.1677ed0.8896752506ed4402a0519d23b8f50a17

#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.

#-------------------------------
# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 6
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
